---
name: "Test Stale PR Closure"

on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: '15 18 * * *'  
  workflow_dispatch:

jobs:
  test_stale_pr:
    uses: TheNova22/ansible-content-actions/.github/workflows/close_stale_issues_pr.yml@close-stale-items
    with:
      days-before-stale: 0
      days-before-close: 0